# Generated by Django 3.2 on 2022-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=20)),
                ('expiration_date', models.DateTimeField()),
                ('check', models.BooleanField(default=True)),
            ],
        ),
    ]
