# Generated by Django 4.1.3 on 2022-11-30 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="RecipeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rc_num", models.IntegerField(blank=True, null=True)),
                ("rc_name", models.CharField(blank=True, max_length=100, null=True)),
                ("rc_view", models.IntegerField(blank=True, null=True)),
                ("rc_rec", models.IntegerField(blank=True, null=True)),
                ("rc_scrap", models.IntegerField(blank=True, null=True)),
                ("rc_type", models.CharField(blank=True, max_length=100, null=True)),
                ("rc_sit", models.CharField(blank=True, max_length=100, null=True)),
                ("rc_sort", models.CharField(blank=True, max_length=100, null=True)),
                ("rc_nick", models.CharField(blank=True, max_length=100, null=True)),
                ("rc_info", models.CharField(blank=True, max_length=100, null=True)),
                ("rc_ing", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "rc_diff",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("아무나", "아무나"),
                            ("초급", "초급"),
                            ("중급", "중급"),
                            ("고급", "고급"),
                            ("신의경지", "신"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "rc_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("5분이내", "오분"),
                            ("10분이내", "십분"),
                            ("15분이내", "십오분"),
                            ("30분이내", "삼십분"),
                            ("60분이내", "한시간"),
                            ("90분이내", "한시간반"),
                            ("2시간이내", "두시간"),
                            ("2시간이상", "두시간이상"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("rc_src", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("recommend", models.IntegerField(blank=True, null=True)),
                ("hook_text", models.CharField(blank=True, max_length=100)),
                ("content", models.TextField()),
                (
                    "head_image",
                    models.ImageField(
                        blank=True, upload_to="ingredients/images/%Y/%m/%d/"
                    ),
                ),
                ("ingredient", models.CharField(blank=True, max_length=200, null=True)),
                ("time", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingredients.categories",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, null=True, to="ingredients.tags"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MnistImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "head_image",
                    models.ImageField(upload_to="ingredients/images/%Y/%m/%d/"),
                ),
                ("result", models.CharField(blank=True, max_length=30)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.CharField(max_length=20)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
