# Generated by Django 3.2 on 2022-11-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_post_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='MnistImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_image', models.ImageField(upload_to='ingredients/images/%Y/%m/%d/')),
                ('result', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='ingredients/images/%Y/%m/%d/'),
        ),
    ]
