# Generated by Django 3.2 on 2022-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20221112_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/images/%Y/%m/%d/'),
        ),
    ]
