# Generated by Django 3.2 on 2022-11-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_recipe_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_num', models.IntegerField(blank=True, null=True)),
                ('rc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_view', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_rec', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_scrap', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_sit', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_sort', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_nick', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_info', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_ing', models.CharField(blank=True, max_length=200, null=True)),
                ('rc_diff', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='recipe_list',
        ),
    ]
